---
- name: IP
  hosts: localhost
  gather_facts: true  # remove later! speeds up testing
  become: true

  tasks:
  - debug:
      msg: "System {{ inventory_hostname }} has IP {{ ansible_all_ipv4_addresses }}"

  - name: get IP
    setup:
    register: result
  - name: print result
    debug: var=item.address
    loop: "{{ result.ansible_facts.ansible_eth0.ipv6 }}"
