---
  - name: install postgres
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
       - postgresql-server

  - name: Check if PostgreSQL database is initialized.
    stat:
      path: /var/lib/pgsql/data/
    register: pgdata_dir_version

  - name: initilize postgres
    command: postgresql-setup initdb

#  - name: Ensure PostgreSQL database is initialized.
#    command: postgresql-setup initdb/initdb -D /var/lib/pgsql/data/
   # when: not pgdata_dir_version.stat.exists

  - name: start postgres
    service:
      name: postgresql.service
      enabled: yes
      state: restarted
