---
  tasks:
  - name: enable repos
    template:
      src: open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644

  tasks:
  - name: http
    yum: 
      name: "{{ item }}"
      state: latest
    with_items:
       - httpie
       - haproxy 
    notify: haproxy_restart

  - name: configure haproxy
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify: haproxy_restart
  - name: haproxy_restart
    service:
      name: haproxy
      state: restarted
